services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"   # Redis DB
      - "8001:8001"   # Redis UI

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"   # Qdrant HTTP API
      - "6334:6334"   # Qdrant gRPC API
